package:
        name: bsstudio
        version: 1.0.0

source:
        path: ..

requirements:
        build:
                - python
                - sip
                - qt
                - pyqtgraph
                - pyqt
                - matplotlib
                - ipython

        run:
                - python
                - sip
                - qt
                - pyqtgraph
                - pyqt
                - matplotlib
                - ipython
