package:
        name: bsstudio
        version: 1.0.0

source:
        path: ..

requirements:
        build:
                - python 3.6
                - sip 4.18.1
                - qt 5.6.3

        run:
                - python 3.6
                - sip 4.18.1
                - qt 5.6.3
